// backend model for events

export const dataSource = {
	ArrayOfDefaultSchedule: {
		DefaultSchedule: [
			{
				AllDay: false,
				Description: "",
				EndTime: " 2023-04-10T10:30:00",
				EndTimeZone: "",
				Id: 100,
				Recurrence: 1,
				RecurrenceEndDate: "",
				RecurrenceRule: "FREQ=DAILY;INTERVAL=2;COUNT=10",
				RecurrenceStartDate: "",
				RecurrenceType: "",
				RecurrenceTypeCount: "",
				StartTime: " 2023-04-10T09:00:00",
				StartTimeZone: "",
				Subject: "Bering Sea Gold",
				RoomId: "26d87e18-dad6-47d8-a998-8281bbebf1da",
				HostID: "39b906aa-bd57-4cfb-aa4c-7c84f7bf9501",
			},
			{
				AllDay: false,
				Categorize: 2,
				CustomStyle: "",
				Description: "",
				EndTime: "2016-02-02T05:00:00",
				EndTimeZone: "",
				Id: 101,
				Location: "mum",
				Owner: 1,
				Priority: "",
				Recurrence: 0,
				RecurrenceEndDate: "",
				RecurrenceRule: "",
				RecurrenceStartDate: "",
				RecurrenceType: "",
				RecurrenceTypeCount: "",
				Reminder: "",
				StartTime: " 2023-02-02T04:00:00",
				StartTimeZone: "",
				Subject: "Bering Sea Gold",
			},
			{
				AllDay: false,
				Categorize: "3,4",
				CustomStyle: "",
				Description: "",
				EndTime: " 2023-02-03T17:30:00",
				EndTimeZone: "",
				Id: 102,
				Location: "trcy",
				Owner: 1,
				Priority: "",
				Recurrence: 0,
				RecurrenceEndDate: "",
				RecurrenceRule: "",
				RecurrenceStartDate: "",
				RecurrenceType: "",
				RecurrenceTypeCount: "",
				Reminder: "",
				StartTime: " 2023-02-03T16:00:00",
				StartTimeZone: "",
				Subject: "Bering Sea Gold",
			},
			{
				AllDay: false,
				Categorize: 3,
				CustomStyle: "",
				Description: "",
				EndTime: " 2023-02-04T04:30:00",
				EndTimeZone: "",
				Id: 103,
				Location: "chn",
				Owner: 1,
				Priority: "",
				Recurrence: 0,
				RecurrenceEndDate: "",
				RecurrenceRule: "",
				RecurrenceStartDate: "",
				RecurrenceType: "",
				RecurrenceTypeCount: "",
				Reminder: "",
				StartTime: " 2023-02-04T03:00:00",
				StartTimeZone: "",
				Subject: "What Happened Next?",
			},
			{
				AllDay: false,
				Categorize: 5,
				CustomStyle: "",
				Description: "",
				EndTime: " 2023-02-05T05:40:00",
				EndTimeZone: "",
				Id: 104,
				Location: "trcy",
				Owner: 1,
				Priority: "",
				Recurrence: 0,
				RecurrenceEndDate: "",
				RecurrenceRule: "",
				RecurrenceStartDate: "",
				RecurrenceType: "",
				RecurrenceTypeCount: "",
				Reminder: "",
				StartTime: " 2023-02-05T05:00:00",
				StartTimeZone: "",
				Subject: "What Happened Next?",
			},
			{
				AllDay: false,
				Categorize: "4,6",
				CustomStyle: "",
				Description: "",
				EndTime: " 2023-02-02T02:00:00",
				EndTimeZone: "",
				Id: 105,
				Location: "chn",
				Owner: 1,
				Priority: "",
				Recurrence: 0,
				RecurrenceEndDate: "",
				RecurrenceRule: "",
				RecurrenceStartDate: "",
				RecurrenceType: "",
				RecurrenceTypeCount: "",
				Reminder: "",
				StartTime: " 2023-02-02T01:00:00",
				StartTimeZone: "",
				Subject: "Daily Planet",
			},
			{
				AllDay: false,
				Categorize: 4,
				CustomStyle: "",
				Description: "",
				EndTime: " 2023-02-07T05:00:00",
				EndTimeZone: "",
				Id: 102,
				Location: "chn",
				Owner: 1,
				Priority: "",
				Recurrence: 0,
				RecurrenceEndDate: "",
				RecurrenceRule: "",
				RecurrenceStartDate: "",
				RecurrenceType: "",
				RecurrenceTypeCount: "",
				Reminder: "",
				StartTime: " 2023-02-07T04:00:00",
				StartTimeZone: "",
				Subject: "Alaska: The Last Frontier",
			},
			{
				AllDay: false,
				Categorize: 1,
				CustomStyle: "",
				Description: "",
				EndTime: " 2023-02-05T02:30:00",
				EndTimeZone: "",
				Id: 107,
				Location: "chn",
				Owner: 1,
				Priority: "",
				Recurrence: 1,
				RecurrenceEndDate: "",
				RecurrenceRule: "FREQ=WEEKLY;BYDAY=MO,TU;INTERVAL=1;COUNT=15",
				RecurrenceStartDate: "",
				RecurrenceType: "",
				RecurrenceTypeCount: "",
				Reminder: "",
				StartTime: " 2023-02-05T02:00:00",
				StartTimeZone: "",
				Subject: "How It's Made",
			},
			{
				AllDay: false,
				Categorize: "2,4",
				CustomStyle: "",
				Description: "",
				EndTime: " 2023-02-08T17:00:00",
				EndTimeZone: "",
				Id: 108,
				Location: "chn",
				Owner: 1,
				Priority: "",
				Recurrence: 0,
				RecurrenceEndDate: "",
				RecurrenceRule: "",
				RecurrenceStartDate: "",
				RecurrenceType: "",
				RecurrenceTypeCount: "",
				Reminder: "",
				StartTime: " 2023-02-08T16:00:00",
				StartTimeZone: "",
				Subject: "Deadest Catch",
			},
			{
				AllDay: false,
				Categorize: "1,3",
				CustomStyle: "",
				Description: "",
				EndTime: " 2023-05-30T07:30:00",
				EndTimeZone: "",
				Id: 109,
				Location: "chn",
				Owner: 1,
				Priority: "",
				Recurrence: 0,
				RecurrenceEndDate: "",
				RecurrenceRule: "",
				RecurrenceStartDate: "",
				RecurrenceType: "",
				RecurrenceTypeCount: "",
				Reminder: "",
				StartTime: " 2023-05-30T02:30:00",
				StartTimeZone: "",
				Subject: "Sports Day",
			},
			{
				AllDay: false,
				Categorize: "3,5",
				CustomStyle: "",
				Description: "",
				EndTime: " 2023-02-09T02:30:00",
				EndTimeZone: "",
				Id: 110,
				Location: "chn",
				Owner: 1,
				Priority: "",
				Recurrence: 1,
				RecurrenceEndDate: "",
				RecurrenceRule: "FREQ=DAILY;INTERVAL=1;COUNT=5",
				RecurrenceStartDate: "",
				RecurrenceType: "",
				RecurrenceTypeCount: "",
				Reminder: "",
				StartTime: " 2023-02-09T02:00:00",
				StartTimeZone: "",
				Subject: "MoonShiners",
			},
			{
				AllDay: false,
				Categorize: "5,3",
				CustomStyle: "",
				Description: "",
				EndTime: " 2023-02-10T15:00:00",
				EndTimeZone: "",
				Id: 111,
				Location: "chn",
				Owner: 1,
				Priority: "",
				Recurrence: 1,
				RecurrenceEndDate: "",
				RecurrenceRule: "FREQ=WEEKLY;BYDAY=MO,TH;INTERVAL=1;COUNT=5",
				RecurrenceStartDate: "",
				RecurrenceType: "",
				RecurrenceTypeCount: "",
				Reminder: "",
				StartTime: " 2023-02-10T14:00:00",
				StartTimeZone: "",
				Subject: "Close Encounters",
			},
			{
				AllDay: false,
				Categorize: "6,1",
				CustomStyle: "",
				Description: "",
				EndTime: " 2023-05-30T03:30:00",
				EndTimeZone: "",
				Id: 112,
				Location: "mum",
				Owner: 1,
				Priority: "",
				Recurrence: 1,
				RecurrenceEndDate: "",
				RecurrenceRule: "FREQ=WEEKLY;BYDAY=WE;INTERVAL=1;COUNT=3",
				RecurrenceStartDate: "",
				RecurrenceType: "",
				RecurrenceTypeCount: "",
				Reminder: "",
				StartTime: " 2023-05-30T03:00:00",
				StartTimeZone: "",
				Subject: "Close Encounters",
			},
			{
				AllDay: false,
				Categorize: "1,4",
				CustomStyle: "",
				Description: "",
				EndTime: " 2023-02-11T07:00:00",
				EndTimeZone: "",
				Id: 113,
				Location: "chn",
				Owner: 1,
				Priority: "",
				Recurrence: 0,
				RecurrenceEndDate: "",
				RecurrenceRule: "",
				RecurrenceStartDate: "",
				RecurrenceType: "",
				RecurrenceTypeCount: "",
				Reminder: "",
				StartTime: " 2023-02-11T03:00:00",
				StartTimeZone: "",
				Subject: "Highway Thru Hell",
			},
			{
				AllDay: false,
				Categorize: "2,5",
				CustomStyle: "",
				Description: "",
				EndTime: " 2023-02-12T05:50:00",
				EndTimeZone: "",
				Id: 114,
				Location: "chn",
				Owner: 1,
				Priority: "",
				Recurrence: 0,
				RecurrenceEndDate: "",
				RecurrenceRule: "",
				RecurrenceStartDate: "",
				RecurrenceType: "",
				RecurrenceTypeCount: "",
				Reminder: "",
				StartTime: " 2023-02-12T04:20:00",
				StartTimeZone: "",
				Subject: "Moon Shiners",
			},
			{
				AllDay: false,
				Categorize: 3,
				CustomStyle: "",
				Description: "",
				EndTime: " 2023-02-13T16:30:00",
				EndTimeZone: "",
				Id: 115,
				Location: "chn",
				Owner: 1,
				Priority: "",
				Recurrence: 1,
				RecurrenceEndDate: "",
				RecurrenceRule: "FREQ=DAILY;INTERVAL=1;COUNT=5",
				RecurrenceStartDate: "",
				RecurrenceType: "",
				RecurrenceTypeCount: "",
				Reminder: "",
				StartTime: " 2023-02-13T15:00:00",
				StartTimeZone: "",
				Subject: "Cash Cab",
			},
		],
	},
};